### ISSUE TITLE
Sometimes Unable to Open E+ SQL File

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#103]
From Kyle:

> I think it again goes back to MLEP and specifically that MLEP does not always (or perhaps ever, I'm not sure) allow EnergyPlus to go through the closeout sequence that among many things closes the output files. I won't rule out that there could be some user error and that there could be some missing MLEP api calls that need to be made. But in any case, I think it is safe to say that the root cause is abrupt EnergyPlus termination

**Comment by anyaelena** [comment]
Have not observed this issue since Jan 2021 changes [here](https://github.com/NREL/python-mlep)
