### ISSUE TITLE
Python dependency management for E+ models, including docs

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#110]
Just document:
- The python EMS stuff will be run with Python 3
- Therefore, feel free to use any packages in your EMS that are in the `py3-requirements.txt`

Additionally, document:
- build custom worker w/additional packages
- run E+ through docker as option for modelers to debug python dependencies

**Comment by anyaelena** [comment]
Develop and document workflow for Eric.  Possible `docker run energyplus...` preliminary test to run e+ models through alfalfa worker locally.

**Comment by anyaelena** [comment]
@TShapinsky bump! It sounds like you have a PR ready for this.
