### ISSUE TITLE
Add OSM Tests

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#113]
Add tests into the main Github that have been used for projects. The following will be defined for OSMs (or zipped OSWs), but should think about how to replicate for FMUs as well.

- [ ] TestPointsAvailable: Define points that should be available via the alfalfa api
    - [ ] Are all expected read points available?
    - [ ] Area all expected write points available?
- [ ] TestExternalAdvance: Can the simulation be advanced via an external client.  Two things to check:
    - [ ] The simulation time remains the same for > 1 minute when the client does NOT issue an advance
    - [ ] The simulation time increases by 1 minute when the client does issue an advance
- [ ] TestWriteToAPI: Define values that should be written to specific points of interest and validate that the value retrieved from the API is the written value

**Comment by anyaelena** [comment]
osms no longer supported; only osws.
