### ISSUE TITLE
Support time_scale parameter for FMUs

### ISSUE THREAD

**Issue by kbenne** [NREL/alfalfa#12]
(1)using the time_scale to control the waiting time of BOPTEST. 
By default, time_scale=5, which is 12 seconds of realtime. It means each timestep simulation, the BOPTEST will wait 12 seconds until the control loops being executed.
(2)The link pushed to the repo: https://github.com/NREL/alfalfa/tree/Control_Simu_BOPTEST
(3) commit id: 8ea2d4e1b99108733e15e1f626bf25841368a0ab

**Comment by kbenne** [comment]
https://github.com/NREL/alfalfa/tree/12-fmu-timescale

**Comment by goldcoder01** [comment]
please ignore the APIs folder, which i mixed when i was doing APIs related coding.

**Comment by goldcoder01** [comment]
What is the problem here for the "simulation-time-control-for-boptest"?

**Comment by goldcoder01** [comment]
It looks this is a stale branch. I just deleted the APIs folder and pushed to the repo for future records.
