### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by kbenne** [NREL/alfalfa#13]
We currently interact with Alfalfa via the haystack defined REST API and the graphical user interface. The purpose of this task is to develop a python library to abstract interactions with Alfalfa.

There should be functions to....

1. Upload a model (fmu,osm) to be tagged
1. Start a simulation for a tagged model
1. read outputs for a running simulation
1. set intputs for a running simulation
1. Stop a running simulation
1. Download simulation files for a completed simulation

**Comment by corymosiman12** [comment]
@kbenne @YanfeiNREL seems we can close?  Seems this is accomplished via https://github.com/NREL/alfalfa-client

**Comment by corymosiman12** [comment]
I'm closing.
