### ISSUE TITLE
Make upload id and site id the same value for osm files

### ISSUE THREAD

**Issue by kbenne** [NREL/alfalfa#20]

**Comment by goldcoder01** [comment]
It looks like not working by simply changing the site-id to upload-id. 
I made a test: upload twice the same osm model, the PyMongo Database is alert: duplicate key. It is the same for FMU model.

**Comment by corymosiman12** [comment]
So @YanfeiNREL @kbenne can this be closed?

**Comment by anyaelena** [comment]
Closing.  We can re-open if necessary.
