### ISSUE TITLE
Create Alfalfa Exception classes

### ISSUE THREAD

**Issue by nllong** [NREL/alfalfa#202]
Categorize the types of Exceptions that we throw right now in the worker (and backend?). Once we have categories, then create new Exception classes.

**Comment by anyaelena** [comment]
@TShapinsky was this resolved in job refactor?

**Comment by TShapinsky** [comment]
completed #299 
There remain cases where errors are not triggered when they should be (mostly errors that occur in simulation). Exception classes do now exist
