### ISSUE TITLE
Gather requirements from Venkatesh

### ISSUE THREAD

**Issue by kbenne** [NREL/alfalfa#21]
We specifically want to know if initial demonstrations are going to be osm or fmu based 

if osm we need to know if an api to advance sim is required

if fmu we need a model, consider the ROM in the Modelica Buildings Library

**Comment by goldcoder01** [comment]
Based on Venkatesh's plan, we will go with OSM first, then later adding the FMU+ROM.

**Comment by anyaelena** [comment]
closing
