### ISSUE TITLE
[2/11]  Test out how to Manage Volumes and Dependencies

### ISSUE THREAD

**Issue by laurenklun** [NREL/alfalfa#218]
how to install FMU? Kyle script. in meeting chat 2/3.

https://github.com/NREL/alfalfa/issues/207

**Comment by tijcolem** [comment]
Getting some thoughts down here.  I researched this a bit and I think a found a viable solution for what we are trying to achieve, which is to minimize the worker container size as much as possible by leveraging a volume to contain all the runtime dependencies the worker needs to run a job type (OpenStudio, EnergyPlus and FMU). 

I tested this out running EnergyPlus and this does work.  FMU will be next. 

The process would look as follows: 

### Create the volume: 

1 Use a base ubuntu image that is same as worker container (18.04/20.04) and install all the runtime dependencies needed. For instance, download EnergyPlus, OpenStudio and FMU and install the executables and any runtime dependencies required. 

2 ) Run container and attach a new volume (e.g. `/mnt/shared_libs`) 

3 ) Gather a listing of the `ld.so.conf` defined shared library paths by running `ldconfig -v | grep "^/"` and copy all these directories e.g. (`cp -r --parents /lib/ /mnt/shared_libs/`) to the attached volume.  Also copy the main applications executables (`cp -r --parents /usr/local/EnergyPlus-9-6-0/  /mnt/shared_libs/`) to the volume.  At this point, all the main exes and dynamic libs are all copied onto the same volume. 

### Run worker: 

1 ) Run a base/slim worker container and attach the volume above as read only.  Add in a config file to /etc/ld.so.conf.d/ such that it adds all the new paths to the runtime linker and that it checks these new paths last. For example, a new ld config (alfafa_worker_deps.conf) would be look something like: 
```
/mnt/shared_libs/usr/local/lib
/mnt/shared_libs/usr/local/lib/x86_64-linux-gnu
/mnt/shared_libs/lib/x86_64-linux-gnu
/mnt/shared_libs/usr/lib/x86_64-linux-gnu
```

And the complete list would look like: 
```
ldconfig -v | grep -v ^$'\t'.
/usr/local/lib:
/lib/x86_64-linux-gnu:
/usr/lib/x86_64-linux-gnu:
/mnt/shared_libs/usr/local/lib:
/mnt/shared_libs/lib/x86_64-linux-gnu:
/mnt/shared_libs/usr/lib/x86_64-linux-gnu:
/lib:
/usr/lib:
``` 

2 ) At this point the executables copied in the mounted volume should run. We'll want to make certain the ld path order searches in the custom defined paths last.  As it stands now, there are multiple copies of dynamic libs, which I think is okay provided the ld order is correct. We could also copy over the exact dynamic libs required. This would have an extra step by either manually managing the list or obtaining the dynamic libs ( maybe using `ldd executable`) but that might be hard to distinguish between what was needed at install time vs core libs. 

3 ) Create any other symlinks to make it easier to run and more native vs calling it in the volume. 



## Alternative option: 

Maintain a static list of runtime dependencies and install these into the worker container. The mount would just contain the main executables. This would increase the size of the worker container and also be prone to breaking if one of the main executables created/changed a dependency that is not defined in the static list.

**Comment by tijcolem** [comment]
For now I think we should close this issue. If we get to the point where the scale out becomes too slow as the worker container is so large, I think revisiting this would be worthwhile.
