### ISSUE TITLE
Move dbops to web container only

### ISSUE THREAD

**Issue by nllong** [NREL/alfalfa#220]
The `dbops.js` file is only used by the web container and can be moved into that folder. It appears that this file was designed to be extended by clients but I don't think it is needed functionality at the moment.

https://github.com/NREL/alfalfa/blob/develop/lib/dbops.js

**Comment by nllong** [comment]
@kbenne  -- any issue if I move this file to the javascript front end only?

**Comment by kbenne** [comment]
no. Maybe it could even be eliminated?

**Comment by nllong** [comment]
sweet, thanks! I will try to get rid of it, but will move it first.
