### ISSUE TITLE
docs for 0.2.0 release

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#260]

**Comment by corymosiman12** [comment]
Eagerly awaiting the `0.2.0` release :)

Looks like you all are making some headway on improving the project!

**Comment by anyaelena** [comment]
Great to hear from you @corymosiman12!  We do have a ton of exciting momentum now, both in the core codebase here and application of it (which will bring public notebooks and helm charts).   However, don't get too excited for 0.2.0; this 3/31 release will be mostly under the hood changes to the worker to lay the groundwork for feature improvements (API updates, better logging, scalability, etc) in subsequent releases.
