### ISSUE TITLE
A minor issue (inconsistent URL) when submitting a job from a docker container (e.g., Jupyter notebook) to Alfalfa (deployed to localhost).

### ISSUE THREAD

**Issue by Kang-SungKu** [NREL/alfalfa#284]
Hello,

I am working on a collaborative project across Northeastern University, NREL, and ecobee (called _Whole Energy Home_ project), and one of my goals is to allow the building control simulator (https://github.com/ecobee/building-controls-simulator) to communicate with Alfalfa. I find a potential issue when playing with Alfalfa (deployed to localhost), so would like to report it.

1. Configuration:
- OS (host machine): Windows 11 Enterprise (Version 10.0.22000 Build 22000)
- Alfalfa (v0.1.0) is deployed to localhost, following the instruction (source: https://github.com/NREL/alfalfa/wiki/Deployment)
- Alfalfa-client (v0.1.1) is used to upload a job to Alfalfa. When submitting the job, the Python script is written in a Docker container (Jupyter notebook resides in localhost)
- AlfalfaClient instance is initialized with the IP address of the local machine (i.e., url=**http://172.xx.xx.xx**), as the client cannot directly connect to localhost.

2. Symptom
- When submit the job (i.e., running AlfalfaClient.submit(self, path)), I see ConnectionError below.
`ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /upload-url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f94e1006190>: Failed to establish a new connection: [Errno 111] Connection refused'))`
- Even though the host has been specified as **http://172.xx.xx.xx** when AlfalfaClient is initialized, the error reports that the connection to the host **localhost** has been failed.

3. Reason
- When **alfalfa_client.lib.submit_one** function retrieve the file upload template (following line), https://github.com/NREL/alfalfa-client/blob/876b4cb033fa7b7d7601c1aa486d263a4c26502e/alfalfa_client/lib.py#L119 the retrieved URL (postURL = json['url']) seems to have **localhost** as the URL regardless of the actual URL requested by the client.
- I believe this only happens when Alfalfa is deployed to localhost, but have not tested different conditions.

4. Workaround
- Temporary workaround is to replace **http://localhost** with **http://172.xx.xx.xx** (whatever the URL actually requested) at the location. For example, modifying the line from `postURL = json['url']` to `postURL = json['url'].replace('http://localhost', url)` seems to do the job.

**Comment by TShapinsky** [comment]
@anyaelena in your deployment testing have you ever tried uploading models using the `alfalfa-client` with a non `http://localhost` url?

**Comment by TShapinsky** [comment]
@Kang-SungKu it looks like you may need to set your `S3_URL` or `S3_URL_EXTERNAL` to point to your bucket. That is where the url is getting populated from.

**Comment by Kang-SungKu** [comment]
I see. Then I guess the best practice is to access Alfalfa from a remote location (especially in case the IP address of Alfalfa might change) would be using a DDNS service and assign `S3_URL` `S3_URL_EXTERNAL` accordingly. I appreciate your clarification!
