### ISSUE TITLE
Job abstraction for the frontend

### ISSUE THREAD

**Issue by kbenne** [NREL/alfalfa#297]
@TShapinsky is developing a really nice abstraction for Jobs on the worker side. I was thinking it might be nice to have a corresponding abstraction on the frontend (e.g. web container). The possible features might be.

1. Interface to pop a job onto the queue with a message payload.
2. Immediately return a unique identifier for the job.
3. Provide an interface to check in on the job and see if it is running.
4. Interface to retrieve a result body returned by a completed job

Over in Boptest we basically go through these exact steps when starting a new test (except for asking for a return body) https://github.com/ibpsa/project1-boptest/blob/boptest-service/web/server/src/controllers/testcase.js#L63 but without much of an abstraction.

**Comment by anyaelena** [comment]
discuss 7/7 whether to include in 0.4.0
