### ISSUE TITLE
EnergyPlus error on OSM simulation

### ISSUE THREAD

**Issue by MaDooSan** [NREL/alfalfa#32]
Running `steposm/step_osm.py` manually inside the worker container with relevant simulation parameters causes the EnergyPlus program to error out:

Script:

`subprocess.call(['python3.5', 'steposm/step_osm.py', siteRef, realtime, timescale, startDatetime, endDatetime, externalClock])`

Output:

`INFO:botocore.credentials:Found credentials in environment variables.
Server started on 127.0.0.1:43873
Wrote socket.cfg
Launch EnergyPlus
Program terminated: EnergyPlus Terminated--Error(s) Detected.
/usr/local/bin/runenergyplus: line 603: /usr/local/bin/ReadVarsESO: No such file or directory
/usr/local/bin/runenergyplus: line 604: /usr/local/bin/ReadVarsESO: No such file or directory
/usr/local/bin/runenergyplus: line 612: /usr/local/bin/HVAC-Diagram: No such file or directory
`
It appears to be looking in the wrong place as /usr/local/bin/ does not have symlinks to the PreProcess and PostProcess folders in the EnergyPlus directory. Manually creating symlinks to ReadVarsESO and HVAC-Diagram do not help either and cause the following error:

`
INFO:botocore.credentials:Found credentials in environment variables.
Server started on 127.0.0.1:34135
Wrote socket.cfg
Launch EnergyPlus
Program terminated: EnergyPlus Terminated--Error(s) Detected.
`

Are any further changes required in order to run steposm manually? Also, recommended debugging guidelines and locations of error logs would be greatly appreciated.

Thanks,
Madhu

**Comment by MaDooSan** [comment]
Here is the mlep.log:
`
***** NOTE: This script is marked as deprecated as of August 2015.
*****       The functionality of this script is now in the command line interface.
*****       For information on the command line interface:
*****        - See the documentation (https://energyplus.net/documentation)
*****        - Call the application for usage: EnergyPlus --help
*****        - Refer to the man page: man EnergyPlus
*****       In a future version of EnergyPlus, this script will no longer be packaged.

=============== EnergyPlus =================
   Input file  : 5e137921dac2304708c884aa.idf
   Weather file: /simulate/5e137921dac2304708c884aa/workflow/files/weather.epw
ExpandObjects Started.
No expanded file generated.
ExpandObjects Finished. Time:     0.040

=============== EnergyPlus =================
   Input file  : 5e137921dac2304708c884aa.idf
EnergyPlus Starting
EnergyPlus, Version 9.1.0-08d2e308bb, YMD=2020.01.06 18:29
**FATAL:Errors found in getting EMS Runtime Language input. Preceding condition causes termination.
EnergyPlus Run Time=00hr 00min  0.22sec
 ReadVarsESO program starting.
 EOF encountered during read of ESO header records
 probable EnergyPlus error condition -- check eplusout.err
 ReadVarsESO program terminated.
 ReadVars Run Time=00hr 00min  0.01sec
 ReadVarsESO program starting.
 EOF encountered during read of ESO header records
 probable EnergyPlus error condition -- check eplusout.err
 ReadVarsESO program terminated.
 ReadVars Run Time=00hr 00min  0.01sec
  Started HVAC Diagram
  Complete

EnergyPlus output files are located in: "/simulate/5e137921dac2304708c884aa/workflow/run/Output"
`

**Comment by corymosiman12** [comment]
Hey @MaDooSan - sorry I was not getting notified of issues on this.  Is this error still occurring?  I am potentially having a similar issue, so wanted to try and compare notes.

**Comment by corymosiman12** [comment]
New issue created: https://github.com/NREL/alfalfa/issues/44

**Comment by MaDooSan** [comment]
Hi @corymosiman12 I haven't seen this error again since I rolled back some changes and tried a fresh osm upload. Will look into it and get back to you.

**Comment by corymosiman12** [comment]
@MaDooSan seems this can be closed?
