### ISSUE TITLE
container_name for worker in docker-compose prevents scaling

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#330]
To reproduce, deploy via docker-compose and attempt to scale worker.

**Comment by TShapinsky** [comment]
I believe this line prevents scaling https://github.com/NREL/alfalfa/commit/f748d6f1155267b28bf78072d3db38567e561268#diff-9542f82d64bbeebd91f6236324bfe199e9657e2cb1fd9779d5d6dcdcf9cd4de1R49 as it locks the container name and docker tries to instantiate multiple containers with the same name and fails

**Comment by TShapinsky** [comment]
Oh I misread this a bit. You had already figured out the problem.

**Comment by TShapinsky** [comment]
I'm not tired
