### ISSUE TITLE
Determine correct behavior for empty write arrays

### ISSUE THREAD

**Issue by axelstudios** [NREL/alfalfa#354]
There are currently two different behaviors when handling new empty writeArrays: In both cases the empty writeArray is inserted, but one instance disables `writeStatus` and the other sets it to `ok`.  It's not clear which is the correct behavior

## onPointWriteArray
https://github.com/NREL/alfalfa/blob/7f7797c174516f5f54dfd3b734dbd4ebd79ff58d/alfalfa_web/server/alfalfa-server.js#L478-L479

## writePoint
https://github.com/NREL/alfalfa/blob/7f7797c174516f5f54dfd3b734dbd4ebd79ff58d/alfalfa_web/server/dbops.js#L121-L122

**Comment by anyaelena** [comment]
Let's set `status:ok` since `disabled` is supposed to indicate a manual disable (https://project-haystack.org/doc/lib-phIoT/writeStatus)
