### ISSUE TITLE
Refactor step_sim and run_sim functions

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#40]

**Comment by corymosiman12** [comment]
Create root class, for which classes in both step_osm and step_fmu inherit from - something like:
- ModelAdvancer()
- OSMModelAdvancer(ModelAdvancer)
- FMUModelAdvancer(ModelAdvancer)

Define args required for passing into run the actual advancer, as specified by: https://github.com/NREL/alfalfa/blob/159cedd894f292c78f423511a724d8cab8ca0d46/worker/worker.py#L218

**Comment by anyaelena** [comment]
can i close this?

**Comment by corymosiman12** [comment]
Yes - I think these were mainly notes for refactoring.
