### ISSUE TITLE
Alfalfa Exception: EMS variables starting with numeric characters.

### ISSUE THREAD

**Issue by tanushree04** [NREL/alfalfa#407]
DOE Prototype Buildings are erroring out with an alfalfa exception when uploaded to the alfalfa cctwin server due to EMS variables staring with numeric characters.

To Reproduce:

Upload model attached to alfalfa: https://cctwin.nrel.gov/ using the following simulation parameters

start_dt = datetime.datetime(2021, 7, 1, 0, 0, 0)
end_dt = datetime.datetime(2021, 7, 1, 1, 0, 0)

params = {
    "external_clock": False,
    "timescale": 20,
    "start_datetime": start_dt,
    "end_datetime": end_dt
}

The error is attached:
[LargeHotel.txt](https://github.com/NREL/alfalfa/files/10719131/LargeHotel.txt)
[MediumOffice.txt](https://github.com/NREL/alfalfa/files/10719155/MediumOffice.txt)

Model attached here:
[LargeHotel.zip](https://github.com/NREL/alfalfa/files/10719135/LargeHotel.zip)
[MediumOffice.zip](https://github.com/NREL/alfalfa/files/10719156/MediumOffice.zip)

**Comment by bonnema** [comment]
This is expected behavior. From the [documentation](https://bigladdersoftware.com/epx/docs/22-2/ems-application-guide/variables.html#variables): "variables can be alpha numeric strings but should NOT start with a numeric." Maybe a check is needed to replace these with a `var_` or something.
