### ISSUE TITLE
mlep_decode error

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#44]
Zip output from Alfalfa attached.  Issues are as follows:
1. Model uploads fine
1. Upon start, status changes from 'Stopped' to 'Starting'
1. However, doesn't get to 'Running', just goes back to 'Stopped'

Branch: `cbi`

Issue seems to be occurring in the mlep decoder, per line from logs:
```
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    | Launch EnergyPlus
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    | Traceback (most recent call last):
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    |   File "steposm/step_osm.py", line 427, in <module>
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    |     [ep.flag, eptime, outputs] = mlep.mlep_decode_packet(packet)
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    |   File "/root/steposm/mlep/mlep_decode_packet.py", line 95, in mlep_decode_packet
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    |     packet = packet.decode("utf-8")
alfalfa_worker.1.kjhgoo5mavhf@1lv11inten05    | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte
```

This seems strange, since the mlep client doesn't seem to have been updated since:
```
cmosiman-34078s:alfalfa cmosiman$ git log worker/steposm/mlep/mlep_decode_packet.py
commit 92420e35c8166780dfa4b2e436fcbac062c9a053
Author: Kyle Benne <kyle.benne@nrel.gov>
Date:   Mon Jun 24 11:23:24 2019 -0500

    Cleanup file names and organize
```

Additionally, I am able to get other OSM files to run.  Not sure how to proceed on bug fixes - @willybernal @kbenne any thoughts?

[eb469b60-52b6-11ea-b07d-357d7d00448a.zip](https://github.com/NREL/alfalfa/files/4222793/eb469b60-52b6-11ea-b07d-357d7d00448a.zip)

**Comment by MaDooSan** [comment]
Hi Cory,
I was looking at the eb469b60-52b6-11ea-b07d-357d7d00448a.err log in the Output folder and saw this:

Erl program line text: IF REAL_RTU_FAN_POWER_ENABLE == 1
   **   ~~~   ** Error message:  *** Error: EvaluateExpression: Variable = 'REAL_RTU_FAN_POWER_ENABLE' used in expression has not been initialized! *** 

Could it be why the simulation errors out and stops?

**Comment by corymosiman12** [comment]
Yeah, true, could be.  I guess that potentially could lead to an decode error on mlep side?  Good catch!

**Comment by MaDooSan** [comment]
Happy to help :)

**Comment by corymosiman12** [comment]
Nice catch Madhu.

Summary:

Upon further inspection, it was noticed that certain EMS variables had not been correctly initialized.  version3 of the file is now working.  Both files attached.

Diffing the two files:
`$ diff RTUcord_Jan2020_version2.osm RTUcord_Jan2020_version3.osm`

Results in:
```
<   IF RTU_6_Cooling_Mode_Enable == 1,      !- Program Line 1
---
>   IF RTU_6_Cooling_Mode_CMD_Enable == 1,      !- Program Line 1
12231c12231
<   RTU_1_Real_RTU_SA_Drybulb_Temperature_CMD_Enable, !- Name
---
>   RTU_1_Real_RTU_SA_Drybulb, !- Name
12269c12269
<   IF RTU_1_Cooling_Mode_Enable == 1,      !- Program Line 1
---
>   IF RTU_1_Cooling_Mode_CMD_Enable == 1,      !- Program Line 1
12470c12470
<   IF RTU_5_Cooling_Mode_Enable == 1,      !- Program Line 1
---
>   IF RTU_5_Cooling_Mode_CMD_Enable == 1,      !- Program Line 1
12659c12659
<   IF RTU_2_Cooling_Mode_Enable == 1,      !- Program Line 1
---
>   IF RTU_2_Cooling_Mode_CMD_Enable == 1,      !- Program Line 1
12848c12848
<   IF RTU_4_Cooling_Mode_Enable == 1,      !- Program Line 1
---
>   IF RTU_4_Cooling_Mode_CMD_Enable == 1,      !- Program Line 1
13037c13037
<   IF RTU_3_Cooling_Mode_Enable == 1,      !- Program Line 1
---
>   IF RTU_3_Cooling_Mode_CMD_Enable == 1,      !- Program Line 1
13090c13090
<   IF Real_RTU_Fan_Power_Enable == 1,      !- Program Line 1
---
>   IF Real_RTU_Fan_Power_CMD_Enable == 1,      !- Program Line 1
13131c13131
<   IF Real_RTU_CoolingCoil_Power_Enable == 1, !- Program Line 1
---
>   IF Real_RTU_CoolingCoil_Power_CMD_Enable == 1, !- Program Line 1
```

[Archive.zip](https://github.com/NREL/alfalfa/files/4223318/Archive.zip)
