### ISSUE TITLE
Migrate Historian from InfluxDB to REDIS Streams?

### ISSUE THREAD

**Issue by TShapinsky** [NREL/alfalfa#483]
If we use REDIS streams to communicate run outputs we get historian functionality for free. 

Caveat is that Redis Stream operations are classified as "slow". Influxdb writes are currently a major component limiting the maximum speed of runs in Alfalfa.

**Comment by anyaelena** [comment]
Discussion today: 
1. NREL Alfalfa deployments will likely integrate with broader data analysis and viz tooling for ARIES
2. For now, main historian-related pain point is ability to download history CSV from alfalfa-client

**Comment by anyaelena** [comment]
wait, you completed this?

**Comment by TShapinsky** [comment]
> wait, you completed this?

Oh no, it wasn't supposed to say complete. I was just closing because we decided that we wouldn't go down this route.

**Comment by anyaelena** [comment]
gotcha!  thanks for all the cleanup!
