### ISSUE TITLE
Alfalfa measure not working in v0.7.0

### ISSUE THREAD

**Issue by saltshaker** [NREL/alfalfa#519]
When I tried updated to v0.7.0, my Alfalfa measures that work on the previous version no longer work. The error, included below, indicates an issue with the `report_inputs_outputs` method in alfalfa_mixin.rb using the JSON module. I noticed the gemspec for alfalfa-lib-gem still points to ruby 2.7 despite OpenStudio 3.8 updating to ruby 3.2. Has something superseded the gem for adding inputs and outputs to Alfalfa?

```
Traceback (most recent call last):
eval:416:in `const_missing'
/alfalfa/alfalfa_worker/jobs/openstudio/lib/alfalfa-lib-gem/lib/alfalfa_mixin.rb:31:in `block in report_inputs_outputs'
eval:493:in `open'
/alfalfa/alfalfa_worker/jobs/openstudio/lib/alfalfa-lib-gem/lib/alfalfa_mixin.rb:30:in `report_inputs_outputs'
/runs/c1f23460-4ad5-11ef-9b8a-f737417ccd54/home/psalter/Documents/Leadville/leadville_community/community_sim/building_models/11/measures/example_model_measure/measure.rb:97:in `run'
[openstudio.workflow.OSWorkflow] <Error> Found error in state 'OpenStudioMeasures' with message: 'Runner error: Measure '/runs/c1f23460-4ad5-11ef-9b8a-f737417ccd54/home/psalter/Documents/Leadville/leadville_community/community_sim/building_models/11/measures/example_model_measure/measure.rb' reported an error with [SWIG director method error. NameError: uninitialized constant OpenStudio::Alfalfa::AlfalfaMixin::JSON

Traceback (most recent call last):
eval:416:in `const_missing'
/alfalfa/alfalfa_worker/jobs/openstudio/lib/alfalfa-lib-gem/lib/alfalfa_mixin.rb:31:in `block in report_inputs_outputs'
eval:493:in `open'
/alfalfa/alfalfa_worker/jobs/openstudio/lib/alfalfa-lib-gem/lib/alfalfa_mixin.rb:30:in `report_inputs_outputs'
/runs/c1f23460-4ad5-11ef-9b8a-f737417ccd54/home/psalter/Documents/Leadville/leadville_community/community_sim/building_models/11/measures/example_model_measure/measure.rb:97:in `run']'
```

**Comment by TShapinsky** [comment]
Hi @saltshaker The gemspec isn't relevant at this point as the gem is not being compiled it is just included. Alfalfa 0.7.0 is compatible with OS 3.8.0 with ruby 3.2. 

Could you post your measure? it looks like you're somehow referring to `OpenStudio::Alfalfa::AlfalfaMixin::JSON` which is not an object that exists. 

Make sure you return true at the end of your `run` method as os 3.8.0 not requires that.

**Comment by saltshaker** [comment]
[measure.txt](https://github.com/user-attachments/files/16398069/measure.txt)

Yeah, here's the measure I'm using. I don't believe I'm referring to the JSON object anywhere and I'm returning true.

**Comment by TShapinsky** [comment]
@saltshaker I can't see anything weird in the measure, which is weird. The bit of code that does JSON serialization is run on every model and I've never seen this error in our test suite. Would it be possible for you to send me the whole model zip so I can try it on my deployment?

**Comment by saltshaker** [comment]
[model.zip](https://github.com/user-attachments/files/16432752/model.zip)
Here's one of the models I'm using.

**Comment by TShapinsky** [comment]
Hi @saltshaker I finally got a chance to look at this and there is indeed a problem in the alfalfa code, though it's not new for 0.7.0. I'll get a patch out hopefully next week, but until that happens you can fix your measure by just adding `require 'json'` at the top. Hopefully this helps!

**Comment by saltshaker** [comment]
Thank you for your help with this!
