### ISSUE TITLE
Travis builds are failing due to new new caps on free accounts

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#82]
`Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.`

Note that build allowances are shared across the entire NREL org.  We should likely explore alternatives.

**Comment by corymosiman12** [comment]
@anyaelena Nick & SEED team migrated over to using Github actions: https://github.com/SEED-platform/seed/blob/develop/.github/workflows/ci.yml

Hopefully useful as a reference.
