### ISSUE TITLE
Better handling of errors on worker.

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#83]
For example:
1. E+ errors during upload kill worker.
2. E+ errors during simulation warm up orphan sim in "Starting" state.

Implement after #202

**Comment by corymosiman12** [comment]
On this note - in the event something does get stuck in 'starting' or 'stopping' state, there seems to be now way to do a rolling reset.  On the server where this is running, I tried restarting services individually (`docker service update alfalfa_worker` ...) as well as doing a rolling redeployment (`docker stack deploy alfalfa`).  The 'stopping' simulation remained.  The only way to get this to work was to remove the stack and redeploy. Is that right? Maybe we can add some docs for how to get this to work.

**Comment by anyaelena** [comment]
We should add integration test(s) with Alfalfa-incompatible osw (i can provide example)

**Comment by anyaelena** [comment]
#299
