### ISSUE TITLE
Test that date times are in expected format.

### ISSUE THREAD

**Issue by anyaelena** [NREL/alfalfa#92]
see #90

**Comment by corymosiman12** [comment]
Hi @anyaelena also related to this:

https://github.com/NREL/alfalfa/blob/79503a6518160f1250edb50e8672f7dfdd7d712e/tests/integration/test_single_zone_vav_fmu.py#L20-L21

I think on the alfalfa-client we should require that the start and end datetime should either be a:
- datetime.datetime object
- iso8601 formatted string

I will plan to throw validation errors for that

**Comment by corymosiman12** [comment]
@anyaelena, there are multiple places in the application where we probably need to be clear / validate expectations:
- When the web API receives a post request to start a simulation
- When the web API posts a message to the Queue
- When a message is retrieved from the Queue by the worker https://github.com/NREL/alfalfa/blob/4ef15135c5d16c2bfb8e1267176374a1becb42b1/alfalfa_worker/worker.py#L64
- When a subprocess is spawned by the main worker to perform a stepped simulation https://github.com/NREL/alfalfa/blob/eac858dc175255e5e24f762bd913500881edd08d/alfalfa_worker/worker.py#L210
- When the subprocess arguments are verified upon call: https://github.com/NREL/alfalfa/blob/4ef15135c5d16c2bfb8e1267176374a1becb42b1/alfalfa_worker/step_sim/step_sim_utils.py#L14


Might have missed some but this should be a good starting point.
