### ISSUE TITLE
Unspecified error when reading from Socket

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#95]
- branch: gh-actions
- test: TestSmallOfficeOSM

The subprocess.call looks as follows:
```
worker_1  | INFO:alfalfa_worker:Calling step_sim_type subprocess: ['python3', 'step_sim/step_osm.py', '0013d61a-4a47-11eb-b784-3af9d38d2919', 'timescale', '2019-01-02 00:00:00', '2019-01-03 00:00:00', '--step_sim_value=5']
```

Following the worker logs when running this integration test, I get:
```
worker_1  | Error: Unspecified error when reading from socket.
```

The test still 'passes', however, I'm not sure if it's because:
- The error isn't getting raised back to the client so it 'seems ok'
- If this isn't really an error and it's actually working as expected

My guess is that this error is being raised from the mlep.start(), since I can't find the error message anywhere in alfalfa or mlep and this is the only generic error:
- https://github.com/NREL/python-mlep/blob/38c9c920dd77e37fa239a703247261d8878f7a0c/mlep/mlep_process.py#L143-L151

**Comment by kbenne** [comment]
> My guess is that this error is being raised from the mlep.start(),

@corymosiman12 yes I think you are write. I think this is the failure mode you will see anytime there is an EnergyPlus fatal error. Certainly not a very user friendly failure mode is it?

**Comment by anyaelena** [comment]
Believe this was fixed in python-MLEP update.
