### ISSUE TITLE
GraphQL API: String cannot represent value

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#97]
Sending:
```
mutation {
  writePoint(
    siteRef: "04783f8c-4a76-11eb-819c-3af9d38d2919",
    pointName: "Real_RTU_Fan_Mode_CMD",
    value: 1,
    level: 2
  )
}
```
I know both the siteRef and the pointName exist else I would get this:
`"message": "Cannot read property '_id' of null",`

Error:
```
{
  "errors": [
    {
      "message": "String cannot represent value: { _id: \"18c416c8-4a76-11eb-b86a-02420a000110\", val: [1, 1, null, null, null, null, null, null, null, null, ... 7 more items], who: [null, null, null, null, null, null, null, null, null, null, ... 7 more items], siteRef: \"04783f8c-4a76-11eb-819c-3af9d38d2919\" }",
      "locations": [
        {
          "line": 31,
          "column": 3
        }
      ],
      "path": [
        "writePoint"
      ]
    }
  ],
  "data": {
    "writePoint": null
  }
}
```

I'm assuming this has to do with the writePoint endpoint being defined as a `GraphQLString` but actually getting returned an object:
https://github.com/NREL/alfalfa/blob/eac858dc175255e5e24f762bd913500881edd08d/alfalfa_web/server/schema.js#L275-L277

**Comment by corymosiman12** [comment]
I know for cbi streamsets we are hitting the `/api/writePoint` end point based on the [haystack spec](https://project-haystack.org/doc/Ops#pointWrite).  What is the expected / preferred way to actually write values to the api?

**Comment by anyaelena** [comment]
Will deprecate GraphQL
