### ISSUE TITLE
OSM Model Advancer should check 'is not None'

### ISSUE THREAD

**Issue by corymosiman12** [NREL/alfalfa#98]
https://github.com/NREL/alfalfa/blob/eac858dc175255e5e24f762bd913500881edd08d/alfalfa_worker/step_sim/osm_model_advancer.py#L385

In Python, `bool(0)` evaluates to `False`.  Therefore, in the scenario where val is a zero, this expression evaluates to `False` and the `_Enable` does not get set to 1.  This should match the fmu implementation:
https://github.com/NREL/alfalfa/blob/eac858dc175255e5e24f762bd913500881edd08d/alfalfa_worker/step_sim/step_fmu.py#L235

**Comment by corymosiman12** [comment]
Fixed for both cbi and gh-actions/develop branch.

**Comment by anyaelena** [comment]
thank you @corymosiman12 !
